Mon, 07 Jul 2025 17:04:09-root-log.py-[line:224]-ERROR-[日志信息]: 无法定位到该元素('xpath', "//input[@name='uaddress']").异常为：
Message: 
Stacktrace:
	GetHandleVerifier [0x0x7ff67e846f65+76917]
	GetHandleVerifier [0x0x7ff67e846fc0+77008]
	(No symbol) [0x0x7ff67e5f9dea]
	(No symbol) [0x0x7ff67e650256]
	(No symbol) [0x0x7ff67e65050c]
	(No symbol) [0x0x7ff67e6a3887]
	(No symbol) [0x0x7ff67e6784af]
	(No symbol) [0x0x7ff67e6a065c]
	(No symbol) [0x0x7ff67e678243]
	(No symbol) [0x0x7ff67e641431]
	(No symbol) [0x0x7ff67e6421c3]
	GetHandleVerifier [0x0x7ff67eb1d29d+3051437]
	GetHandleVerifier [0x0x7ff67eb178f3+3028483]
	GetHandleVerifier [0x0x7ff67eb3588d+3151261]
	GetHandleVerifier [0x0x7ff67e86182e+185662]
	GetHandleVerifier [0x0x7ff67e8696ef+218111]
	GetHandleVerifier [0x0x7ff67e84fae4+112628]
	GetHandleVerifier [0x0x7ff67e84fc99+113065]
	GetHandleVerifier [0x0x7ff67e836c68+10616]
	BaseThreadInitThunk [0x0x7ffb6b1ae8d7+23]
	RtlUserThreadStart [0x0x7ffb6c49c34c+44]

Mon, 07 Jul 2025 17:50:48-root-log.py-[line:224]-ERROR-[日志信息]: 执行sql出现错误，异常为list index out of range
Mon, 07 Jul 2025 17:51:05-root-log.py-[line:224]-ERROR-[日志信息]: 执行sql出现错误，异常为list index out of range
Mon, 07 Jul 2025 17:55:12-root-log.py-[line:224]-ERROR-[日志信息]: 执行sql出现错误，异常为near "s": syntax error
Mon, 07 Jul 2025 17:55:28-root-log.py-[line:224]-ERROR-[日志信息]: 执行sql出现错误，异常为near "s": syntax error
Mon, 07 Jul 2025 17:55:46-root-log.py-[line:224]-ERROR-[日志信息]: 执行sql出现错误，异常为near "s": syntax error
Mon, 07 Jul 2025 18:02:21-root-log.py-[line:224]-ERROR-[日志信息]: 执行sql出现错误，异常为list index out of range
Mon, 07 Jul 2025 18:05:49-root-log.py-[line:224]-ERROR-[日志信息]: 执行sql出现错误，异常为list index out of range
Mon, 07 Jul 2025 18:10:16-root-log.py-[line:224]-ERROR-[日志信息]: 执行sql出现错误，异常为can only concatenate list (not "int") to list
Mon, 07 Jul 2025 18:10:24-root-log.py-[line:224]-ERROR-[日志信息]: 执行sql出现错误，异常为can only concatenate list (not "str") to list
